### ISSUE TITLE
其它模块怎么使用user , pay 的服务？

### ISSUE THREAD

**Issue by xiangtao** [G-little/priest#17]

**Comment by xiangtao** [comment]
其它模块怎么使用user , pay 的服务？

**Comment by G-little** [comment]
如果要使用 user的认证，只需要将拦截器放入http 模块就可以了

**Comment by G-little** [comment]
目前pay只实现了基本的账户间转账，交易记录，微信，支付宝的接入目前我还在开发中

**Comment by xiangtao** [comment]
@G-little 我的意思是，如果其它模块要调用 user或者pay 模块是通过rest接口调用还是 dubbo接口？ ，如果是dubbo的话，rest接口就只能是每个模块孤立的了。

**Comment by G-little** [comment]
这个是rest 接口和 dubbo 接口都有的，rest 对外提供业务，dubbo 接口负责内部dubbo 服务的业务信息修改或者获取，因为最近不太有时间，还没有来得及梳理支付和用户的接口文档，后面我给加上的。
