### ISSUE TITLE
感觉这个分包分的有点看不懂

### ISSUE THREAD

**Issue by lixiaofeng0316** [G-little/priest#19]
dubbo服务最佳实践：建议将服务接口、服务模型、服务异常等均放在 API 包中，因为服务模型和异常也是 API 的一部分，这样做也符合分包原则：重用发布等价原则(REP)，共同重用原则(CRP)。
我现在不明白这句话，目前感觉应该是按服务模块划分api包，api包里面放接口和模型，对应的异常和校验。

**Comment by G-little** [comment]
你的感觉是对的呢，确实这样，按模块划分 api 包，api 包里包含接口和模型 和对应的异常，至于公共的异常和模型，放到公共包里就可以了呢。
